### ISSUE TITLE
Plugin does not build against the current gerrit HEAD

### ISSUE THREAD

**Issue by ugodiggi** [vadims/gerrit-owners#4]
Reported from nikos.michalakis@gmail.com

Looks like the BUILD files I wrote have now been outlawed, I see the following:

```
$ buck build gerrit plugins/gerrit-owners/gerrit-owners:owners
remote: Counting objects: 5094, done
remote: Finding sources: 100% (14906/14906)
remote: Total 14906 (delta 9195), reused 14906 (delta 9195)
Receiving objects: 100% (14906/14906), 41.23 MiB | 4.82 MiB/s, done.
Resolving deltas: 100% (9195/9195), completed with 393 local objects.
From https://gerrit.googlesource.com/buck
   6e2e783..c38b989  github-master -> origin/github-master
Buck is at 274acb17e9b6dc9ee60bc1371c47a7f49640c24c,
but should be c38b9899f7952382963cb7822bbdfc9104b42e70.
Buck is updating itself.
To disable this, add a '.nobuckcheck' file to your project root.
In general, you should only disable this if you are developing Buck.
Previous HEAD position was 274acb1... Allow system wide or user specific configurations
HEAD is now at c38b989... Add a brief "Tour of the Codebase" document.
Buildfile: /Users/ugo/development/buck/build.xml

clean:
   [delete] Deleting directory /Users/ugo/development/buck/build

BUILD SUCCESSFUL
Total time: 0 seconds
Buck does not appear to have been built -- building Buck!
Not using buckd because watchman isn't installed.
[+] PARSING BUCK FILES...0.2s
Traceback (most recent call last):
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 1227, in <module>
    main()
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 455, in main
    values = buildFileProcessor.process(build_file.rstrip())
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 395, in process
    implicit_includes=self._implicit_includes)
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 386, in _process_build_file
    implicit_includes=implicit_includes)
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 350, in _process
    exec(code, module.__dict__)
  File "/Users/ugo/development/gerrit/plugins/gerrit-owners/gerrit-owners/BUCK", line 1, in <module>
    include_defs('//plugins/gerrit-owners/common.defs')
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 274, in _include_defs
    implicit_includes=implicit_includes)
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 367, in _process_include
    implicit_includes=implicit_includes)
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 350, in _process
    exec(code, module.__dict__)
  File "/Users/ugo/development/gerrit/plugins/gerrit-owners/common.defs", line 8, in <module>
    license = 'Apache2.0',
  File "/Users/ugo/development/gerrit/lib/maven.defs", line 92, in maven_jar
    out = binjar,
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 92, in invoke
    return self.func(*args, **updated_kwargs)
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 811, in genrule
    }, build_env)
  File "/Users/ugo/development/gerrit/buck-out/tmp/buck_run.Ie9Fxv/buck179844315429781973.py", line 103, in add_rule
    .format(rule['type']))
AssertionError: Cannot use `genrule()` at the top-level of an included file.
[2014-11-03 22:00:55.052][error][command:d0edb3de-7819-4d9a-92f6-7279c2dabb55][tid:01][com.facebook.buck.json.ProjectBuildFileParser] Process java.lang.UNIXProcess@1f939fd3 exited with error code 1
BUILD FAILED: Parse error for BUCK file /Users/ugo/development/gerrit/plugins/gerrit-owners/gerrit-owners/BUCK: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was END_DOCUMENT at line 2 column 1
```

I'm looking into this.

**Comment by BevinYe** [comment]
Hi,

I just tested with this patch. It can successfully generate the plugin jar file owners.jar.
However, when trying to put the jar into gerrit/plugins/ folder, it shows error:

[2015-03-04 16:48:34,900] WARN  com.google.gerrit.server.plugins.PluginLoader : Plugin owners tries to @null("null") abstract class com.google.gerrit.rules.PrologEnvironment$Factory
[2015-03-04 16:48:34,900] WARN  com.google.gerrit.server.plugins.PluginLoader : Plugin owners tries to @null("null") abstract class com.google.gerrit.rules.PredicateProvider
[2015-03-04 16:48:34,900] WARN  com.google.gerrit.server.plugins.PluginLoader : Plugin owners tries to @null("null") abstract class com.google.gerrit.rules.PrologCompiler$Factory
[2015-03-04 16:48:34,901] WARN  com.google.gerrit.server.plugins.PluginLoader : Plugin owners tries to @null("null") abstract class com.google.gerrit.audit.AuditListener
[2015-03-04 16:48:35,029] WARN  com.google.gerrit.server.plugins.PluginLoader : Cannot load plugin owners
com.google.gerrit.server.plugins.InvalidPluginException: Cannot register com.google.gerrit.server.securestore.DefaultSecureStore, server does not accept com.google.gerrit.server.securestore.SecureStore
	at com.google.gerrit.server.plugins.AutoRegisterModules.listen(AutoRegisterModules.java:216)
	at com.google.gerrit.server.plugins.AutoRegisterModules.listen(AutoRegisterModules.java:226)
	at com.google.gerrit.server.plugins.AutoRegisterModules.export(AutoRegisterModules.java:151)
	at com.google.gerrit.server.plugins.AutoRegisterModules.scan(AutoRegisterModules.java:115)
	at com.google.gerrit.server.plugins.AutoRegisterModules.discover(AutoRegisterModules.java:76)
	at com.google.gerrit.server.plugins.ServerPlugin.startPlugin(ServerPlugin.java:180)
	at com.google.gerrit.server.plugins.ServerPlugin.start(ServerPlugin.java:167)
	at com.google.gerrit.server.plugins.PluginLoader.runPlugin(PluginLoader.java:460)
	at com.google.gerrit.server.plugins.PluginLoader.rescan(PluginLoader.java:389)
	at com.google.gerrit.server.plugins.PluginLoader.start(PluginLoader.java:294)
	at com.google.gerrit.lifecycle.LifecycleManager.start(LifecycleManager.java:74)
	at com.google.gerrit.pgm.Daemon.start(Daemon.java:291)
	at com.google.gerrit.pgm.Daemon.run(Daemon.java:203)
	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:166)
	at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:93)
	at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:50)
	at Main.main(Main.java:25)

**Comment by ugodiggi** [comment]
Hey Bevin, haven't touched this in a little bit, but I will have to upgrade my own gerrit sometime in the near future. I hope to test this over the weekend and make it functional with gerrit's latest release.

**Comment by ugodiggi** [comment]
So I'm currently testing a fix for this.
I have a version that build out on my fork, will test and will create a pull-request once it is working.
https://github.com/ugodiggi/gerrit-owners

**Comment by ugodiggi** [comment]
My pull request https://github.com/vadims/gerrit-owners/pull/5 should fix this issue.

**Comment by drtechniko** [comment]
Hi Ugo,
I was able to install the plug-in fine this time. Thanks!

I am however using the jenkins plug-in to add a "Verified" label. What I
notice now is that instead of seeing the Verified label and the
Owner-Approval label from the owners plug-in I see instead the jenkins user
added to my reviewers automatically.

Is there some config I need to modify for the owners plug-in?

Also, one of our developers is wondering if we can do owners per file
instead of per directory. Is that possible?

thanks again for fixing this.

**Comment by drtechniko** [comment]
My bad. I remembed you had sent me instructions to add a rules.pl file and
troubleshoot. Let me try that before I waste your time about the label
issue.
I'd still be interested to know if there is a way to do ownership per file.

**Comment by drtechniko** [comment]
Update: after I used the rules.pl from the README I got this to work as
advertised (i.e., ownership per directory).

**Comment by ugodiggi** [comment]
I'm not super fresh with the code, so everything is iirc.
The code currently is only supporting directory level ownership, the bulk of the code is in:

https://github.com/vadims/gerrit-owners/blob/master/gerrit-owners-common/src/main/java/com/vmware/gerrit/owners/common/PathOwners.java
and of course the ownership model is https://github.com/vadims/gerrit-owners/blob/master/gerrit-owners-common/src/main/java/com/vmware/gerrit/owners/common/OwnersConfig.java

I think it would be easy-ish to change the code to add ownership by file.
Personally I would not want to have such a feature in my code base, though, since I prefer separating in multiple directories.

**Comment by vadims** [comment]
I'm not sure about per file OWNERS, but at the time we considered adding support for OWNERS per language..

```yaml
inherited: true
owners:
- user-a@example.com
- user-b@example.com
files:
- pattern: *.java
  owners:
    - user-c@example.com
- pattern: *.js
  owners:
  - user-d@example.com
```

**Comment by drtechniko** [comment]
Thanks Ugo.

I just wanted to know if you supported it. That's all. We have a fully
working gerrit with owners now so I'm good :)

Thanks for your help guys.

nikos
